/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_keylane_JniTest */

#ifndef _Included_com_keylane_JniTest
#define _Included_com_keylane_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_keylane_JniTest
 * Method:    mul
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_keylane_JniTest_mul
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
